"""Generate ``results/BOUNDARY_TABLE.md`` from ``results/boundary_sweep.yaml``.

Standing constraint S11 forbids hand-typing a number into a markdown file. The
negative-result addendum in ``audit/MMC_COMPOSITION_SPEC.md`` and the session report both
need to state what the boundary sweep found, so the table is generated here and quoted
there, exactly as ``src/diagnostics/report_tables.py`` and ``report_k6.py`` already do for
the diagnostic and the K = 6 spectrum.

Nothing is computed here that is not already in the YAML. This module formats.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

import yaml

REPO = Path(__file__).resolve().parents[2]
SRC = REPO / "results" / "boundary_sweep.yaml"
OUT = REPO / "results" / "BOUNDARY_TABLE.md"

KEYS = ("AAA|studentised", "BBB|studentised", "AAA|plain", "BBB|plain")
PRIMARY = "AAA|studentised"


def key_md(k: str) -> str:
    """A case key inside a markdown table cell. The ``|`` separating assignment from variant
    is also the column separator, so it has to be escaped or the table silently loses a
    column and every heading after it shifts."""
    return "`" + k.replace("|", r"\|") + "`"


def fmt(p: float) -> str:
    if p == 0.0:
        return "**0**"
    if p >= 0.01:
        return f"{p:.4f}"
    return f"{p:.2e}"


def rows(doc: dict[str, Any]) -> list[dict[str, Any]]:
    """One row per width, plus the ``w = 0`` anchor, in one shape."""
    out = [{
        "width": 0.0,
        "shift_median": 0.0,
        "shift_over_noise": 0.0,
        "by_key": {k: doc["anchor_theta0"][k] for k in KEYS},
        "n_dead": {k: 0 for k in KEYS},
        "n_points": 1,
    }]
    for e in doc["per_width"]:
        out.append({
            "width": e["width"],
            "shift_median": e["nuisance_shift_norm_of_mean_z"]["median"],
            "shift_over_noise": e["nuisance_shift_norm_of_mean_z"]["median_over_noise"],
            "by_key": e["by_key"],
            "n_dead": {k: e["by_key"][k]["n_design_points_with_a_dead_cell"] for k in KEYS},
            "n_points": e["n_design_points"],
        })
    return out


def last_width_with(rs: list[dict[str, Any]], key: str, verdict: str) -> float | None:
    hits = [r["width"] for r in rs if r["by_key"][key]["gate"]["verdict"] == verdict]
    return max(hits) if hits else None


def first_width_with(rs: list[dict[str, Any]], key: str, verdict: str) -> float | None:
    hits = [r["width"] for r in rs if r["by_key"][key]["gate"]["verdict"] == verdict]
    return min(hits) if hits else None


def render(doc: dict[str, Any]) -> str:
    rs = rows(doc)
    s = doc["settings"]
    L: list[str] = []
    A = L.append
    A("<!-- GENERATED by src/diagnostics/report_boundary.py from results/boundary_sweep.yaml.")
    A("     Do not edit. Standing constraint S11: no number in a markdown file is typed by hand. -->")
    A("")
    A("### The boundary sweep — where the selection cells stop being reachable")
    A("")
    A(f"Session G7, `OUTSTANDING.md` O-30. Summary set `{s['summary_set']}`, "
      f"{s['n_grid_points']} design points over {len(s['widths'])} half-widths plus the "
      f"`theta_0` anchor, {s['n_simulator_runs']:,} simulator runs, "
      f"{s['wall_clock_seconds']:.0f} s.")
    A("")
    A("**This sweep is characterisation. It does not reopen `docs/DECISIONS.md` D-16**, which "
      "was decided before the script that produced these numbers was written.")
    A("")

    # ---- 1. the primary series -----------------------------------------------------------
    A(f"#### 1. The primary case — {key_md(PRIMARY)}, the worst validated assignment")
    A("")
    A("`p_min(w)` is the minimum over the design and over the `K` selection cells: the "
      "quantity `audit/MMC_COMPOSITION_SPEC.md` §4 point 1 says the cost is governed by.")
    A("")
    A("| half-width `w` | median ‖E[z]‖ | ÷ noise √d | `p_min(w)` | 95% CI | cell | dead cells | gate |")
    A("|---|---|---|---|---|---|---|---|")
    for r in rs:
        b = r["by_key"][PRIMARY]["reported_min"]
        g = r["by_key"][PRIMARY]["gate"]["verdict"]
        ci = f"{b['ci95'][0]:.2e} – {b['ci95'][1]:.2e}"
        dead = ("—" if r["width"] == 0.0
                else f"{r['n_dead'][PRIMARY]}/{r['n_points']}")
        w = "0 (`θ₀`)" if r["width"] == 0.0 else f"{r['width']:g}"
        A(f"| {w} | {r['shift_median']:.2f} | {r['shift_over_noise']:.2f} | {fmt(b['p_sel'])} | "
          f"{ci} | {b['cell']} | {dead} | **{g}** |")
    A("")
    noise = doc["per_width"][0]["nuisance_shift_norm_of_mean_z"]["single_draw_noise_magnitude_sqrt_d"]
    A(f"`√d = {noise:.4f}` is the magnitude of a single null draw's normalised discrepancy, by "
      "construction: every summary coordinate is divided by its prior-predictive standard "
      "deviation. The third column is therefore the nuisance-shift-to-noise ratio, which is "
      "the quantity the mechanism turns on.")
    A("")

    # ---- 2. where the gate turns ----------------------------------------------------------
    A("#### 2. Where the pre-registered gate turns, per case")
    A("")
    A("| case | last `w` at PASS (all four corners) | first `w` at FAIL (no corner) | shape | slope ratio | log-linear `b` (decades per unit `w`) | `R²` |")
    A("|---|---|---|---|---|---|---|")
    for k in KEYS:
        sh = doc["shape_of_the_collapse"][k]
        fit = sh.get("loglinear_fit") or {}
        lp = last_width_with(rs, k, "PASS")
        ff = first_width_with(rs, k, "FAIL")
        ratio = sh["slope_ratio"]
        cells = [
            key_md(k),
            "—" if lp is None else f"{lp:g}",
            "—" if ff is None else f"{ff:g}",
            f"**{sh['shape']}**",
            "—" if ratio is None else f"{ratio:.2f}",
            f"{fit['slope_b_decades_per_unit_half_width']:.1f}" if fit.get("fitted") else "—",
            f"{fit['r_squared']:.3f}" if fit.get("fitted") else "—",
        ]
        A("| " + " | ".join(cells) + " |")
    A("")
    A(f"The shape criterion is pre-registered in `src/diagnostics/boundary_sweep.py`: **ABRUPT** "
      f"iff the largest local log-slope is at least "
      f"{doc['shape_of_the_collapse'][PRIMARY]['slope_ratio_threshold']:g}× the median one, "
      f"**GRADUAL** otherwise, and **CENSORED_BELOW** if fewer than four widths have "
      f"`p_min > 0`. `R²` is reported and is not part of the criterion.")
    A("")
    A("| case | steepest interval | live widths |")
    A("|---|---|---|")
    for k in KEYS:
        sh = doc["shape_of_the_collapse"][k]
        si = sh.get("steepest_interval")
        A(f"| {key_md(k)} | {('—' if not si else f'{si[0]:g} – {si[1]:g}')} | {sh['n_live_widths']} |")
    A("")

    # ---- 3. the other three cases ---------------------------------------------------------
    A("#### 3. `p_min(w)` for all four cases")
    A("")
    A("| `w` | " + " | ".join(key_md(k) for k in KEYS) + " |")
    A("|---|" + "---|" * len(KEYS))
    for r in rs:
        w = "0 (`θ₀`)" if r["width"] == 0.0 else f"{r['width']:g}"
        A(f"| {w} | " + " | ".join(
            fmt(r["by_key"][k]["reported_min"]["p_sel"]) for k in KEYS) + " |")
    A("")

    # ---- 4. the checks --------------------------------------------------------------------
    c = doc["checks"]
    A("#### 4. The checks this sweep had to pass, and what each would have taken to fail")
    A("")
    A("| check | value | what makes it FALSE |")
    A("|---|---|---|")
    A(f"| `normalisation_reproduces` | {c['normalisation_reproduces']} | the prior-predictive "
      f"mean or sd recomputed here differing from `results/jacobian_rank.S_B.yaml` by more than "
      f"{c['normalisation_max_relative_difference']['tolerance']:g} relatively. The run aborts |")
    A(f"| `jacobian_reproduces` | {all(c['jacobian_reproduces'].values())} | no recorded step "
      f"size reproducing the singular values `results/robustness/k6_spectrum.yaml` records |")
    A(f"| `family_sets_agree_at_zero` | {c['family_sets_agree_at_zero']} | the two family "
      f"branches differing at `η = 0`, so one set of null draws could not serve both |")
    A(f"| `seed_spans_disjoint_from_G6` | {c['seed_spans_disjoint_from_G6']} | any seed span "
      f"here overlapping one recorded in `results/p_sel.yaml`. The run aborts, because a "
      f"reproduction check on shared draws is not a check |")
    A(f"| `theta0_reproduces_recorded_p_sel` | {c['theta0_reproduces_recorded_p_sel']} "
      f"(max \\|z\\| = {c['theta0_max_abs_z']:.2f} against {c['theta0_z_threshold']:g}) | a "
      f"two-proportion `z` above the threshold on any of the twelve `(key, cell)` comparisons "
      f"against `results/p_sel.yaml`, on draws the two runs do not share |")
    A(f"| `w005_reproduces_the_recorded_collapse` | "
      f"{c['w005_reproduces_the_recorded_collapse']} | this run finding acceptances at "
      f"`w = 0.05`, where G6 found none in 100,000 draws. That would be a finding about the "
      f"recorded zero, not a defect here |")
    A(f"| `shape_is_determined` | {all(c['shape_is_determined'].values())} | fewer than four "
      f"widths with `p_min > 0`, i.e. the boundary lying below the smallest width swept |")
    A("")
    A(f"**`theta0_inside_recorded_ci95_alone` reads "
      f"{c['theta0_inside_recorded_ci95_alone']}, and it is not a reproduction test.** It is "
      f"the check this script shipped in its first version, retained rather than deleted. See "
      f"`DEVIATIONS.md` **D-17**.")
    A("")
    p = doc["provenance"]
    A(f"*Generated from `results/boundary_sweep.yaml` — script `{p['script']}`, commit "
      f"`{p['commit'][:7]}`, dirty `{p['dirty']}`, seed `{p['seed']}`.*")
    return "\n".join(L) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="generate results/BOUNDARY_TABLE.md")
    ap.add_argument("--src", default=str(SRC))
    ap.add_argument("--out", default=str(OUT))
    args = ap.parse_args(argv)
    doc = yaml.safe_load(Path(args.src).read_text(encoding="utf-8"))
    Path(args.out).write_text(render(doc), encoding="utf-8")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
