"""Re-run the Phase 2 diagnostic under a different distortion family set, or a different seed.

WHY THIS EXISTS
---------------
Session G3 produced a favourable separability verdict for ``S_A`` and ``S_B``. Its own report
named two reasons that verdict might not mean what it appears to:

  * **the families.** The verdict is a statement about the three specific distortion families
    G3 chose, not about the simulator (``audit/S3_REPORT.md`` §4.4, **Q-12**);
  * **the seed.** The diagnostic was run once, at one seed, so no seed-to-seed stability of the
    *verdict* had been computed (**O-18**).

This script tests both, and it is deliberately thin. It does **not** re-implement the
diagnostic: it calls the same :func:`~src.diagnostics.jacobian_rank.estimate_jacobian` and
:func:`~src.diagnostics.jacobian_rank.analyse` with the same pre-registered thresholds, the
same ``h`` sweep, the same normalisation rule and the same replicate count that
``run_diagnostic.py`` uses. **The only things that vary are the family set and the seed.**
That is the whole point: a re-run that also adjusted the estimator would not test the verdict,
it would test a different estimator.

WHAT IT WRITES, AND WHERE
-------------------------
Into ``results/robustness/``, never into ``results/`` itself. G3's five results files are the
record of what G3 ran and are not overwritten, amended or regenerated by this script.

Usage
-----
    python -m src.diagnostics.run_family_check --families adversarial --label adversarial
    python -m src.diagnostics.run_family_check --families base --seed 20260821 --label seed2
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from ..provenance import header, now_iso
from ..simulators import sir3
from ..simulators.sir3 import COMPONENTS, K, prior_predictive_stats, with_params
from ..simulators.summaries import SUMMARY_LABELS, SUMMARY_SETS
from .jacobian_rank import (
    COHERENCE_FLAG,
    COLNORM_INVISIBLE,
    H_VALUES,
    KAPPA_MAX,
    PLATEAU_REL_TOL,
    RESOLVE_FACTOR,
    TAU,
    VK_MIN,
    analyse,
    estimate_jacobian,
)

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "results" / "robustness"

FAMILY_DESCRIPTIONS: dict[str, dict[str, str]] = {
    "base": {
        "transmission": "beta*S*I/N -> beta*S*I/N / (1 + eta_1*(I/N)/p_ref)   [saturating incidence; prevalence nonlinearity]",
        "progression": "gamma -> gamma*exp(eta_2*(t/T - 0.5))   [mean-centred log-linear hazard drift; timing/trend]",
        "observation": "rho -> rho*exp(eta_3)   [reporting-fraction multiplier; pure amplitude]",
    },
    "adversarial": {
        "transmission": "beta -> beta*exp(eta_1)   [constant rate multiplier; TARGETS progression via the beta/gamma aliasing]",
        "progression": "gamma -> gamma*exp(-eta_2)   [constant rate multiplier, sign-aligned so eta_1 and eta_2 move R0 the same way; TARGETS transmission]",
        "observation": "rho -> rho*exp(eta_3*(t/T - 0.5))   [mean-centred log-linear reporting trend; TARGETS both, via the observed growth rate]",
    },
}

ADVERSARIAL_INTENT = (
    "This family set was designed to FAIL. Each family was chosen against a named target "
    "component before the run, on the reasoning recorded in the sir3.py module docstring: all "
    "three columns perturb the same dominant feature of an epidemic curve (its observed "
    "exponential growth rate), where the base set perturbs three qualitatively different "
    "features. If the pass verdict survives this, that is evidence the base verdict was not an "
    "artefact of a favourable family choice. If it does not survive, the base verdict is a "
    "statement about three chosen families and must be written as one."
)


def _write(path: Path, doc: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        yaml.safe_dump(doc, fh, sort_keys=False, default_flow_style=False, width=100)
    print(f"wrote {path.relative_to(REPO)}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--families", choices=("base", "adversarial"), default="adversarial")
    ap.add_argument("--label", required=True, help="filename tag, e.g. 'adversarial' or 'seed2'")
    ap.add_argument("--seed", type=int, default=20260820)
    ap.add_argument("--replicates", type=int, default=128)
    ap.add_argument("--norm-replicates", type=int, default=2000)
    args = ap.parse_args(argv)

    command = "python -m src.diagnostics.run_family_check " + " ".join(
        f"--{k.replace('_', '-')} {v}" for k, v in vars(args).items()
    )
    started = now_iso()
    params = with_params(families=args.families)
    seed_norm = args.seed + 900_000
    p_ref = sir3.peak_prevalence_fraction(params)

    print(f"[{args.label}] families={args.families} seed={args.seed}: prior-predictive sd ...")
    stats = prior_predictive_stats(SUMMARY_SETS, n_replicates=args.norm_replicates,
                                   seed0=seed_norm, params=params)
    sd_map = {name: sd for name, (_m, sd) in stats.items()}
    mean_map = {name: m for name, (m, _sd) in stats.items()}

    print(f"[{args.label}] h-sweep over {list(H_VALUES)} with R={args.replicates} ...")
    sweeps = estimate_jacobian(SUMMARY_SETS, sd_map, h_values=H_VALUES,
                               n_replicates=args.replicates, seed0=args.seed,
                               params=params, crn=True)

    verdicts = {}
    for name in SUMMARY_SETS:
        a = analyse(sweeps[name])
        verdicts[name] = a
        doc: dict[str, Any] = {
            "provenance": header(script="src/diagnostics/run_family_check.py",
                                 command=command, seed=args.seed, started=started),
            "what_this_is": (
                "ROBUSTNESS RE-RUN, session G4. NOT a replacement for results/jacobian_rank."
                f"{name}.yaml, which records what session G3 ran and is untouched. Same "
                "diagnostic code, same pre-registered thresholds, same h sweep, same "
                "normalisation rule, same replicate count; only the distortion family set "
                "and/or the seed differ. See audit/G3_ADVERSARIAL_REVIEW.md."
            ),
            "run_label": args.label,
            "family_set": args.families,
            "summary_set": name,
            "summary_coordinate_labels": list(SUMMARY_LABELS[name]),
            "component_labels": list(COMPONENTS),
            "distortion_families": FAMILY_DESCRIPTIONS[args.families],
            "distortion_identity_at_zero": (
                "delta_k(.;0) == base simulator exactly for BOTH family sets, tested in "
                "tests/test_sir3.py"
            ),
            "p_ref_peak_prevalence_fraction": float(p_ref),
            "normalisation": {
                "rule": "each summary coordinate divided by its prior-predictive sd at eta = 0",
                "n_replicates_R_norm": int(args.norm_replicates),
                "seed0": int(seed_norm),
                "prior_predictive_sd": [float(x) for x in sd_map[name]],
                "prior_predictive_mean": [float(x) for x in mean_map[name]],
                "note": (
                    "The prior-predictive normalisation is estimated at eta = 0, where every "
                    "distortion family is the identity, so it does NOT depend on which family "
                    "set is selected. It is re-estimated here anyway rather than reused, so "
                    "this file stands on its own run."
                ),
            },
            "estimator": {
                "scheme": "central differences, J[:,k] = mean_r [s(+h e_k; seed_r) - s(-h e_k; seed_r)] / (2h) / sd",
                "common_random_numbers": True,
                "n_replicates_R": int(args.replicates),
                "seed0": int(args.seed),
                "n_simulator_runs": int(sweeps[name].n_simulations),
                "noise_model": "lognormal",
            },
            "thresholds_pre_registered": {
                "source": "docs/THRESHOLDS.md, unchanged; identical to the G3 run",
                "tau_rank_tolerance": TAU,
                "kappa_max": KAPPA_MAX,
                "colnorm_invisible": COLNORM_INVISIBLE,
                "coherence_flag": COHERENCE_FLAG,
                "vk_min_equivalence_class": VK_MIN,
                "resolve_factor": RESOLVE_FACTOR,
                "h_values": list(H_VALUES),
                "plateau_rel_tol": PLATEAU_REL_TOL,
            },
            "results": a,
        }
        if args.families == "adversarial":
            doc["adversarial_intent"] = ADVERSARIAL_INTENT
        _write(OUT / f"jacobian_rank.{args.label}.{name}.yaml", doc)

    print(f"\n[{args.label}] verdicts:")
    for n in SUMMARY_SETS:
        v = verdicts[n]
        print(f"  {n}: {'INSEPARABLE' if v['inseparable'] else 'separable'} "
              f"| rank {v['numerical_rank']['rank_certain']}/{K} "
              f"| kappa {v['condition_number']:.4g} "
              f"| {v['inseparable_reason']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
